
hostnames:
  - energo-alternativa-ru-khusamov.c9users.io
  - energo-alternativa.ru
  - www.energo-alternativa.ru

title: Компания ООО «Альтернатива»

public: [copyright, contacts, getMainPhone]

created: 2011

copyright: '&copy; 2011&ndash;2014 гг., ООО «Альтернатива», Москва, Зеленоград'

getMainPhone: !!js/function >
  function() {
    return this.contacts.phones[0];
  }

contacts:
  address: 124575, Россия, Москва, г. Зеленоград, ул. Панфилова, дом 28, литера Б, строение 1, офис 23.
  email: info@energo-alternativa.ru
  phones:
    - phone: +7 (495) 961-43-74
      person: Александр
    - phone: +7 (926) 625-33-61